# Generated by Django 2.2 on 2019-07-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2.0, default=29.9, max_digits=20),
        ),
    ]
